name: CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
      - name: Test
        run: ./gradlew check
